### PR TITLE
Mediumday10

### PR DESCRIPTION
**Pull request by ashutosh-3474**
# description
solved medium day 10 task

### CODE REVIEW

**Comment by gangwarsomya** [comment]
@ashutosh-3474  your solution is giving tle if  you can optimize it. get it reassign .

**Comment by gangwarsomya** [comment]
@ashutosh-3474  your solution is giving tle, if you can optimize it get it reassign

**Comment by ashutosh-3474** [comment]
@gangwarsomya i want to retry kindly give assign it again

**Comment by gangwarsomya** [comment]
ohk...

**Pull request closed without merging**
